export const settingsModel = {
    diet: ['Balanced', 'High-Fiber', 'High-Protein', 'Low-Carb', 'Low-Fat', 'Low-Sodium'],
    health: [
     'Alcohol-free',
     'Immune-Supportive',
     'Celery-free',
     'Crustcean-free',
     'Dairy',
     'Eggs',
     'Fish',
     'FODMAP free',
     'Gluten',
     'Keto',
     'Kidney friendly',
     'Kosher',
     'Low potassium',
     'Lupine-free', 
     'Mustard-free',
     'n/a',
     'No oil added',
     'No-sugar',
     'Paleo', 
     'Peanuts',
     'Pescatarian',
     'Pork-free', 
     'Red meat-free',
     'Sesame-free', 
     'Shellfish',
     'Soy',
     'Sugar-conscious', 
     'Tree Nuts',
     'Vegan',
     'Vegetarian',
     'Wheat-free'
    ],
    cuisine: [
     'American',
     'Asian',
     'British',
     'Caribbean',
     'Central Europe',
     'Chinese',
     'Eastern Europe',
     'French',
     'Indian',
     'Italian',
     'Japanese',
     'Kosher', 
     'Mediterranean',
     'Mexican',
     'Middle Eastern', 
     'Nordic',
     'South American',
     'South East Asian'
    ],
    dish: [
     'Alcohol-cocktail',
     'Biscuits and cookies',
     'Bread',
     'Cereals',
     'Condiments and sauces',
     'Drinks',
     'Desserts',
     'Egg',
     'Main course',
     'Omelet',
     'Pancake',
     'Preps',
     'Preserve',
     'Salad',
     'Sandwiches',
     'Soup',
     'Starter'
    ],
    meal: ['Breakfast', 'Lunch', 'Dinner', 'Snack', 'Teatime']
}